#!/usr/bin/env python

import os
import sys

binaryPath = sys.path[0] + "/SmartCommit.exe"
# binaryPath = sys.path[0] + "/../dist_electron/win-unpacked/SmartCommit.exe"
os.system(binaryPath)
print("Farewell~")