#!/usr/bin/env python

import os
# path = "C:/Documents and Settings/Program Files/"
# os.chdir(path)
# repo_path = os.getcwd()
# -r repo_path
# os.system("F:/workspace/dev/SmartCommit/dist/SmartCommit-win32-x64/SmartCommit.exe --repo=%s" % repo_path)

os.system("F:/workspace/dev/SmartCommit/vue-app/dist_electron/win-unpacked/SmartCommit.exe")
print("Farewell~")