#!/usr/bin/env python
## for testing

import os
import sys

binaryPath = "C:/Users/Name/AppData/Local/Programs/SmartCommit/SmartCommit.exe"
# binaryPath = sys.path[0] + "/../dist_electron/win-unpacked/SmartCommit.exe"
os.system(binaryPath)
print("Farewell~")